version: '3.7'

services:
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: DockerFile
    image: bake-a-cake-server
    container_name: bake-a-cake-node-server
    command: node index.js
    restart: always
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      WAIT_HOSTS: mongo:27017
      NODE_ENV: development
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
    